export interface SubscriptionOption {
  id: string;
  name: string;
  category: string;
}

export const SUBSCRIPTION_OPTIONS: SubscriptionOption[] = [
  { id: "netflix", name: "Netflix", category: "Streaming" },
  { id: "disney-plus", name: "Disney+", category: "Streaming" },
  { id: "hulu", name: "Hulu", category: "Streaming" },
  { id: "max", name: "Max", category: "Streaming" },
  { id: "prime-video", name: "Prime Video", category: "Streaming" },
  { id: "apple-tv-plus", name: "Apple TV+", category: "Streaming" },
  { id: "paramount-plus", name: "Paramount+", category: "Streaming" },
  { id: "peacock", name: "Peacock", category: "Streaming" },
  { id: "youtube-premium", name: "YouTube Premium", category: "Streaming" },
  { id: "youtube-tv", name: "YouTube TV", category: "Streaming" },
  { id: "sling-tv", name: "Sling TV", category: "Streaming" },
  { id: "fubo", name: "Fubo", category: "Streaming" },
  { id: "crunchyroll", name: "Crunchyroll", category: "Streaming" },
  { id: "spotify", name: "Spotify", category: "Music" },
  { id: "apple-music", name: "Apple Music", category: "Music" },
  { id: "amazon-music", name: "Amazon Music", category: "Music" },
  { id: "tidal", name: "Tidal", category: "Music" },
  { id: "deezer", name: "Deezer", category: "Music" },
  { id: "pandora", name: "Pandora", category: "Music" },
  { id: "soundcloud", name: "SoundCloud", category: "Music" },
  { id: "audible", name: "Audible", category: "Books" },
  { id: "kindle-unlimited", name: "Kindle Unlimited", category: "Books" },
  { id: "scribd", name: "Scribd", category: "Books" },
  { id: "medium", name: "Medium", category: "Reading" },
  { id: "new-york-times", name: "The New York Times", category: "News" },
  { id: "wall-street-journal", name: "The Wall Street Journal", category: "News" },
  { id: "washington-post", name: "The Washington Post", category: "News" },
  { id: "financial-times", name: "Financial Times", category: "News" },
  { id: "economist", name: "The Economist", category: "News" },
  { id: "bloomberg", name: "Bloomberg", category: "News" },
  { id: "icloud-plus", name: "iCloud+", category: "Cloud" },
  { id: "google-one", name: "Google One", category: "Cloud" },
  { id: "dropbox", name: "Dropbox", category: "Cloud" },
  { id: "onedrive", name: "OneDrive", category: "Cloud" },
  { id: "box", name: "Box", category: "Cloud" },
  { id: "adobe-creative-cloud", name: "Adobe Creative Cloud", category: "Creative" },
  { id: "canva", name: "Canva", category: "Creative" },
  { id: "figma", name: "Figma", category: "Design" },
  { id: "sketch", name: "Sketch", category: "Design" },
  { id: "notion", name: "Notion", category: "Productivity" },
  { id: "evernote", name: "Evernote", category: "Productivity" },
  { id: "todoist", name: "Todoist", category: "Productivity" },
  { id: "things", name: "Things", category: "Productivity" },
  { id: "microsoft-365", name: "Microsoft 365", category: "Productivity" },
  { id: "google-workspace", name: "Google Workspace", category: "Productivity" },
  { id: "grammarly", name: "Grammarly", category: "Productivity" },
  { id: "1password", name: "1Password", category: "Security" },
  { id: "lastpass", name: "LastPass", category: "Security" },
  { id: "bitwarden", name: "Bitwarden", category: "Security" },
  { id: "nordvpn", name: "NordVPN", category: "Security" },
  { id: "expressvpn", name: "ExpressVPN", category: "Security" },
  { id: "surfshark", name: "Surfshark", category: "Security" },
  { id: "proton", name: "Proton", category: "Security" },
  { id: "github", name: "GitHub", category: "Developer" },
  { id: "gitlab", name: "GitLab", category: "Developer" },
  { id: "jetbrains", name: "JetBrains", category: "Developer" },
  { id: "cursor", name: "Cursor", category: "Developer" },
  { id: "replit", name: "Replit", category: "Developer" },
  { id: "vercel", name: "Vercel", category: "Developer" },
  { id: "netlify", name: "Netlify", category: "Developer" },
  { id: "digitalocean", name: "DigitalOcean", category: "Developer" },
  { id: "aws", name: "AWS", category: "Developer" },
  { id: "openai", name: "OpenAI", category: "AI" },
  { id: "chatgpt", name: "ChatGPT", category: "AI" },
  { id: "claude", name: "Claude", category: "AI" },
  { id: "gemini", name: "Gemini", category: "AI" },
  { id: "perplexity", name: "Perplexity", category: "AI" },
  { id: "midjourney", name: "Midjourney", category: "AI" },
  { id: "runway", name: "Runway", category: "AI" },
  { id: "linkedin-premium", name: "LinkedIn Premium", category: "Career" },
  { id: "coursera", name: "Coursera", category: "Education" },
  { id: "skillshare", name: "Skillshare", category: "Education" },
  { id: "masterclass", name: "MasterClass", category: "Education" },
  { id: "duolingo", name: "Duolingo", category: "Education" },
  { id: "headspace", name: "Headspace", category: "Health" },
  { id: "calm", name: "Calm", category: "Health" },
  { id: "peloton", name: "Peloton", category: "Fitness" },
  { id: "strava", name: "Strava", category: "Fitness" },
  { id: "fitbit-premium", name: "Fitbit Premium", category: "Fitness" },
  { id: "myfitnesspal", name: "MyFitnessPal", category: "Fitness" },
  { id: "classpass", name: "ClassPass", category: "Fitness" },
  { id: "doordash-dashpass", name: "DashPass", category: "Food" },
  { id: "uber-one", name: "Uber One", category: "Transport" },
  { id: "lyft-pink", name: "Lyft Pink", category: "Transport" },
  { id: "instacart-plus", name: "Instacart+", category: "Shopping" },
  { id: "walmart-plus", name: "Walmart+", category: "Shopping" },
  { id: "costco", name: "Costco", category: "Shopping" },
  { id: "amazon-prime", name: "Amazon Prime", category: "Shopping" },
  { id: "apple-arcade", name: "Apple Arcade", category: "Gaming" },
  { id: "xbox-game-pass", name: "Xbox Game Pass", category: "Gaming" },
  { id: "playstation-plus", name: "PlayStation Plus", category: "Gaming" },
  { id: "nintendo-switch-online", name: "Nintendo Switch Online", category: "Gaming" },
  { id: "twitch", name: "Twitch", category: "Gaming" },
  { id: "patreon", name: "Patreon", category: "Creators" },
  { id: "substack", name: "Substack", category: "Creators" },
  { id: "discord-nitro", name: "Discord Nitro", category: "Community" },
  { id: "zoom", name: "Zoom", category: "Communication" },
  { id: "slack", name: "Slack", category: "Communication" },
  { id: "hbo", name: "HBO", category: "Streaming" },
  { id: "mlb-tv", name: "MLB.TV", category: "Sports" },
  { id: "nba-league-pass", name: "NBA League Pass", category: "Sports" },
  { id: "nfl-plus", name: "NFL+", category: "Sports" },
  { id: "espn-plus", name: "ESPN+", category: "Sports" },
];
